name: VillagerEnchantments
version: '${project.version}'
main: me.maplenetwork.villager_enchantments.VillagerEnchantments
api-version: 1.17
author:
    - woliver99
commands:
    VillagerEnchantments:
        description: Shows VillagerEnchantments Commands.